src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $post_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPostDate(): ?\DateTimeInterface
    {
        return $this->post_date;
    }

    public function setPostDate(?\DateTimeInterface $post_date): self
    {
        $this->post_date = $post_date;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostFormType;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DefaultController
 * @package App\Controller
 * @Route("/", name="default.")
 */
class DefaultController extends AbstractController {

	/**
	 * @Route("/", name="index")
	 * @param Request $request
	 *
	 * @return RedirectResponse|Response
	 */
	public function index( Request $request ) {
		$post = new Post();

		$form = $this->createForm( PostFormType::class, $post );

		$form->add( 'submit', SubmitType::class, [
			'label' => 'Create post',
			'attr'  => [
				'class' => 'btn btn-primary'
			]
		] );

		$form->handleRequest( $request );

		if ( $form->isSubmitted() && $form->isValid() ) {
			$post = $form->getData();
			$post->setPostDate( DateTime::createFromFormat( 'Y-m-d H:i:s', date( 'Y-m-d H:i:s' ) ) );
			$post->setUserId($this->getUser());
			$em = $this->getDoctrine()->getManager();

			$em->persist( $post );
			$em->flush();

			$this->addFlash( 'success', 'Post is successfully created!' );

			return $this->redirectToRoute( 'default.index' );
		}

		$posts = $this->getDoctrine()->getRepository( Post::class )->findAll();

		return $this->render( 'default/index.html.twig', [
			'posts' => $posts,
			'form'  => $form->createView()
		] );
	}

	/**
	 * @Route("/delete/{id}", name="delete")
	 * @param $id
	 *
	 * @return RedirectResponse
	 */
	public function delete( $id ) {
		$post = $this->getDoctrine()->getRepository(Post::class)->find($id);

		$em = $this->getDoctrine()->getManager();

		$em->remove($post);
		$em->flush();

		return $this->redirectToRoute( 'default.index' );
	}
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block title %}Homepage{% endblock %}

{% block body %}
  <div class="mb-3 p-5">
    {{ form(form) }}
  </div>
  {% if posts %}
    {% for post in posts %}
      <div class="card m-2">
        <div class="card-header text-center">
          <h4>Title: {{ post.title }}</h4>
        </div>
        <div class="card-body">
          <h4>Body:</h4>
          <p>{{ post.body }}</p>
          <hr>
          <blockquote class="blockquote mb-0">
            <small>Time posted: {{ post.postDate | date('Y-m-d H:i:s') }}</small>
            <br>
            <small>Posted by: {{ post.userId.username }}</small>
          </blockquote>
        </div>
        {% if app.user.id == post.userId.id %}
          <hr>
          <div class="d-flex justify-content-end">
            <a href="{{ path('default.delete', {'id':post.id}) }}" class="btn btn-danger m-2">Delete</a>
          </div>
        {% endif %}
      </div>
    {% endfor %}
  {% else %}
    <p>There are no posts to show!</p>
  {% endif %}
{% endblock %}